name: hbcd-release
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - r-base
  - r-matrix
  - bioconductor-snprelate
  - bioconductor-gdsfmt
  - bioconductor-seqarray
  - bioconductor-seqvartools
  - bioconductor-genesis
  - bioconductor-biocparallel
